### ISSUE TITLE
Add ELL accessor methods

### ISSUE THREAD

**Issue by KyleVaughn** [bkochuna/ners570f24-SpMV#28]
## Definition of done:

**Comment by davidgw-umich** [comment]
I am the reviewer for this issue. You may want to state what tasks are necessary for creating "tester" as well as define what performance means in regards to that "tester."

**Comment by athenafhl** [comment]
> I am the reviewer for this issue. You may want to state what tasks are necessary for creating "tester" as well as define what performance means in regards to that "tester." Overall your issue looks well-defined.

I updated the tasks. Thanks for your advice.

**Comment by MoonBH-UoM** [comment]
Kindy note that ColIdx should be type **int** since padding requires -1 value for colIdx. Please implement accordingly.

**Comment by MoonBH-UoM** [comment]
Please refer https://github.com/bkochuna/ners570f24-SpMV/issues/48#issuecomment-2434112359
I have taken colIdx for padded element as (size of matrix)+1. So size_t tye for colIdx can be retained.

**Comment by MattGranados** [comment]
Hi @athenafhl
I'm the one writing the tests for the ELL accessors. Just wanted to give you a heads up that the tests will need your script to have a working assembleStorage method in order to run properly, but it look like that method wasn't added until just recently in another branch. Lemme know when your branch is updated with the storage methods so I know when to run tests! 

I still haven't _quite_ finished writing up the tests yet though, so no rush!

**Comment by athenafhl** [comment]
> Hi @athenafhl I'm the one writing the tests for the ELL accessors. Just wanted to give you a heads up that the tests will need your script to have a working assembleStorage method in order to run properly, but it look like that method wasn't added until just recently in another branch. Lemme know when your branch is updated with the storage methods so I know when to run tests!
> 
> I still haven't _quite_ finished writing up the tests yet though, so no rush!

Hi -- I was working on ELLaccessor branch first, but it had conflicts with some bugs previous made by other people. Therefore, I merged the branch into ELL branch, which contains almost all of our work for ELL. You can work on that branch now. Sorry for the confusion! (I know there are so many things going on in this issue....

**Comment by MattGranados** [comment]
@athenafhl Was just wondering when to expect a getCoefficients type accessor to be added? It was my understanding at least that the accessor methods should include all of the accessors already listed on this description _in addition to_ another accessor that returns the ELL value for a user specified set of row and column indices.

**Comment by athenafhl** [comment]
I’m not sure as well… I‘ll check other groups’ accessor methods and
update you.

**Comment by athenafhl** [comment]
@MattGranados I updated the accessor method in the new branch ELL-accessor-method. Thank you for reminding me!

**Comment by MattGranados** [comment]
@athenafhl Great, thanks! But can I also trouble you to add in the assembleStorage() methods from the `ELL-assemblage ` branch into `ELL-accessor-method`? My tests will not be able to run unless that method is in the `SparseMatrix_ELL.cpp` file.

**Comment by MattGranados** [comment]
@athenafhl As of now, my tests _should_ be ready to go and I created a new branch `ELL-accessor-method-tests` where you can see the unit test file. As of now everything fails due to the lack of the AssembleStorage() method in your branch, so let me know when its applied so I can properly run the tests!

**Comment by athenafhl** [comment]
> ssembleStorage



> ELL-accessor-met

@MattGranados I merged the assemble method and it's ready to use

**Comment by MattGranados** [comment]
@athenafhl Great! Unfortunately though, it seems like some (maybe all? haven't gone through _each_ one yet) tests are failing. From adding in some print statements, it's looking like this _might_ just be an issue with the AssembleStorage() method and not your accessor implementation; I'll look into it and try to confirm what the cause is.

**Comment by MattGranados** [comment]
@athenafhl I updated your branch with the latest AssembleStorage() method, but ColIdx accessor still appears to fail, however everything else passes.

**Comment by athenafhl** [comment]
> @athenafhl I updated your branch with the latest AssembleStorage() method, but ColIdx accessor still appears to fail, however everything else passes.

@MattGranados I'm not sure why this would happen... Did your test print anything useful about the compared values?

**Comment by athenafhl** [comment]
@MattGranados I think the problem might come from the assemble method. Is there any way to only test the accessor without doing the storage test?
