### ISSUE TITLE
Add assembleStorage and disassembleStorage methods for COO

### ISSUE THREAD

**Issue by KyleVaughn** [bkochuna/ners570f24-SpMV#46]
## Definition of done:

**Comment by eemahler** [comment]
@PengYululu This issue is ready for review.

**Comment by eemahler** [comment]
@PengYululu This task is ready for review. I have pushed my commit to the COO branch.

**Comment by PengYululu** [comment]
@eemahler Thanks for the update. In the cpp assemble, this->_I = new size_t[this->_nnz*sizeof(size_t)]; There are two size_t. Maybe why not directly: this->_I = new size_t[this->_nnz];

**Comment by athenafhl** [comment]
@eemahler Hi -- I'm done with the storage test for COO, and your code did not pass the test. There might be bugs in your void SparseMatrix_COO<fp_type>::assembleStorage()

**Comment by eemahler** [comment]
@PengYululu You're right. Thanks for catching that. I pushed that fix to the branch.

**Comment by eemahler** [comment]
@athenafhl There was indeed a bug in the code that was fixed. Let me know if that change allows the test to succeed.

**Comment by athenafhl** [comment]
> @athenafhl There was indeed a bug in the code that was fixed. Let me know if that change allows the test to succeed.

The test still failed. Would it be index++ instead of index += index?
